---
- hosts: all
  tasks:
    - name: create udev rule to read co2 monitor
      copy:
        dest: /etc/udev/rules.d/60-co2mon.rules
        content: ACTION=="add|change", SUBSYSTEMS=="usb", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="a052", MODE:="0666"
      notify:
        - udevadm reload
        - udevadm trigger
    - name: install system service to run cooyote
      copy:
        dest: /etc/systemd/system/cooyote.service
        content: |
          [Unit]
          Description=Cooyote Web Server
          After=network.target
          
          [Service]
          ExecStart=/usr/local/bin/cooyote
          Restart=always
          User=nobody
          Group=nogroup
          
          [Install]
          WantedBy=multi-user.target
      notify:
        - reload systemd
        - restart cooyote

  handlers:
    - name: udevadm reload
      command: udevadm control --reload

    - name: udevadm trigger
      command: udevadm trigger

    - name: reload systemd
      command: systemctl daemon-reload

    - name: restart cooyote
      systemd:
        name: cooyote
        state: restarted
        enabled: yes
